# Generated by Django 4.2.2 on 2023-08-07 12:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('product_type', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('feature1', models.CharField(max_length=150)),
                ('feature2', models.CharField(max_length=150)),
                ('feature3', models.CharField(max_length=150)),
                ('feature4', models.CharField(max_length=150)),
                ('specs', models.JSONField()),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
