# Generated by Django 4.2.2 on 2023-08-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sub_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
