# Generated by Django 4.2.2 on 2023-08-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
