# Generated by Django 4.2.2 on 2023-08-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='generation',
            field=models.CharField(blank=True, choices=[('12th Gen', '12th gen'), ('8th Gen', '8th gen'), ('9th Gen', '9th gen'), ('10th Gen', '10th gen'), ('11th Gen', '11th gen'), ('13th Gen', '13th gen'), ('No Gen', 'no gen')], max_length=100, null=True),
        ),
    ]
