# Generated by Django 4.2.2 on 2023-08-19 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_product_generation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antivirus', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builderAntivirus', to='pages.product')),
                ('casing', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builderCasing', to='pages.product')),
                ('casingCooler', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builderCasingCooler', to='pages.product')),
                ('cpu_cooler', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builderCPUCooler', to='pages.product')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pcbuilder', to='pages.customer')),
                ('gpu', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builderGPU', to='pages.product')),
                ('headphone', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builderHeadphone', to='pages.product')),
                ('keyboard', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builderKeyboard', to='pages.product')),
                ('monitor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builderMonitor', to='pages.product')),
                ('motherboard', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builderMotherboard', to='pages.product')),
                ('mouse', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builderMouse', to='pages.product')),
                ('os', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builderOs', to='pages.product')),
                ('processor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builderProcessor', to='pages.product')),
                ('psu', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builderPsu', to='pages.product')),
                ('ram', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builderRam', to='pages.product')),
                ('storage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builderStorage', to='pages.product')),
                ('ups', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builderUps', to='pages.product')),
            ],
        ),
    ]
