# Generated by Django 4.2.2 on 2023-08-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_pcbuilder'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbuilder',
            name='generation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcbuilder',
            name='ram_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
