# Generated by Django 4.2.2 on 2023-08-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_pcbuilder_generation_pcbuilder_ram_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ram_type',
            field=models.CharField(blank=True, choices=[('DDR4', 'ddr4'), ('DDR5', 'ddr5'), ('DDR3', 'ddr3')], max_length=100, null=True),
        ),
    ]
