# Generated by Django 4.2.2 on 2023-08-20 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_product_ram_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcbuilder',
            name='antivirus',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builderAntivirus', to='pages.product'),
        ),
        migrations.AlterField(
            model_name='pcbuilder',
            name='casing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builderCasing', to='pages.product'),
        ),
        migrations.AlterField(
            model_name='pcbuilder',
            name='casingCooler',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builderCasingCooler', to='pages.product'),
        ),
        migrations.AlterField(
            model_name='pcbuilder',
            name='cpu_cooler',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builderCPUCooler', to='pages.product'),
        ),
        migrations.AlterField(
            model_name='pcbuilder',
            name='gpu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builderGPU', to='pages.product'),
        ),
        migrations.AlterField(
            model_name='pcbuilder',
            name='headphone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builderHeadphone', to='pages.product'),
        ),
        migrations.AlterField(
            model_name='pcbuilder',
            name='keyboard',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builderKeyboard', to='pages.product'),
        ),
        migrations.AlterField(
            model_name='pcbuilder',
            name='monitor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builderMonitor', to='pages.product'),
        ),
        migrations.AlterField(
            model_name='pcbuilder',
            name='motherboard',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builderMotherboard', to='pages.product'),
        ),
        migrations.AlterField(
            model_name='pcbuilder',
            name='mouse',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builderMouse', to='pages.product'),
        ),
        migrations.AlterField(
            model_name='pcbuilder',
            name='os',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builderOs', to='pages.product'),
        ),
        migrations.AlterField(
            model_name='pcbuilder',
            name='processor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builderProcessor', to='pages.product'),
        ),
        migrations.AlterField(
            model_name='pcbuilder',
            name='psu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builderPsu', to='pages.product'),
        ),
        migrations.AlterField(
            model_name='pcbuilder',
            name='ram',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builderRam', to='pages.product'),
        ),
        migrations.AlterField(
            model_name='pcbuilder',
            name='storage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builderStorage', to='pages.product'),
        ),
        migrations.AlterField(
            model_name='pcbuilder',
            name='ups',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builderUps', to='pages.product'),
        ),
    ]
