# Generated by Django 4.2.2 on 2023-08-26 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(max_length=250)),
                ('message', models.TextField(blank=True, null=True)),
                ('delivery', models.CharField(max_length=250)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orderInfo', to='pages.order')),
            ],
        ),
    ]
